services:
  - type: web
    name: opengravity-bot-safary
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 7860
      - key: NODE_OPTIONS
        value: "--dns-result-order=ipv4first"
