import dotenv from "dotenv";
import path from "path";
import fs from "fs";

dotenv.config();

// --- DECODIFICACIÓN DE SEGURIDAD CON LIMPIEZA PROFUNDA ---
function d(b64: string): string {
  // Decodifica y elimina cualquier espacio o salto de línea invisible
  return Buffer.from(b64, 'base64').toString('utf8').trim();
}

// Llaves codificadas en Base64 con trim() garantizado
const S = {
  T: d("ODcyODkxMDkzNDpBQUhPVWhsekNrUE9LaXVKZW5iYjZ1LT9HN3VfMjUxQ1Z3VQ=="),
  A: d("NzA2NjA0ODI1NA=="),
  G: d("Z3NrX1Q3ZlVydHdNd0s4Q1o2c3FIQVlXR2R5YjNGWWFPZlhPb0h2QWM0OG1aVFJab1N2N21BNA=="),
  O: d("c2stb3ItdjEtYWQ2YTY4MDQ4YTdhMzc0ODI4NTQwZGU2NmU5MTk4NWRjYWViNGM5ODIwNmVkZjUxMjExZTg3NDM4NjBhZTVhNg=="),
  SU: d("aHR0cHM6Ly9wb3ZtZWRtdnptYWd3eWJoc3ZraC5zdXBhYmFzZS5jbw=="),
  SK: d("ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjeUk2SW5OMWNHRmlZWE5sSW5zaWNtVmlJam9pY0c5MmJXVmtiVlowZW0xaFp3bDViR2h6ZG10b0lpd2ljbTlzWlNJNklmRnVvMjRpTENKcFlYUWlPakUzTnpRMU5UTTBNekVzSW1WNGNDSTZNakE1TURFeU9UUXpNVjBfLi0tbHFWUFRMzlVyTzZ5c3RGVVZiTFBDbnNZRlpCMWw3WnU3OW9uUWVZRUE="),
  E: d("c2tfYzhlMDQ4YmU4YzkyYWYwMWMyMzhkOGQwYTNmNzlkYTM1ZWU4Y2E1ZTlmODU4ODdj"),
  GE: d("QUl6YVN5RFF3TDhDZWNoV3VGelUtTksxYkdVcklLdms5Q3BUc3p3"),
  TV: d("dHZseS1kZXYtMUdESlVuLWFKZ3NFcm5vWktTcGxsRW1BaTVDUHdkT3VBMTVFYk02U2ZoRnB0WVhGYw=="),
  JSON: Buffer.from("eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsICJwcm9qZWN0X2lkIjogIm1pYm90dGVsZWdyYW0tYTBiYWEiLCAicHJpdmF0ZV9rZXlfaWQiOiAiZjJkM2M0NDRkN2VlMzcyOTJjNGYwYWJjNjUzNWM0YzRlY2NkZWE1YyIsICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzVyYWFNbG5MNUxHZW1cbi9WaHdoNVUwRzM5SmlTVjVhQ1lMNDBBZmROS1d4T21nMEtQUmZXQkpBRU9vbVp1TWd4K0grRFcvXG54M1UxM2FvSXBxRmFKTDdLaTk0L0xSTHJUckFZMVMxYTcyTWV3YS9scU1NWWk4WHh4OHFweHdBazRzQW9oQzk3bVxcbnVhcUtEeU9PQzhtck1laTJaQVdKSlVORlAzY2s2RnlJNkRnVkZkOVREb2pody9FdzdyQ1hNMUdsaUM5dHVKTzdcc29LWS8rUVo5NnFVckxEcXVIcHlOY3RzQUFhZkcvUTJ3aERpQzZGWUkrZ0dIb1NTMWhybTNZRzJFeWM4YllzeFxuV2FLVFNTS2xKMVJpMEZvcThCYk9Fck42Wld2cmsyVGtPaFlZaXgrQ2NWVE9Ed0xQTldsQTF1cnlRbDBO頗vOHpNcFxuTXdQWUI5anJBZ01CQUFFQ2dnRUFBN1RNQTZlUVQ2dGZ0N3BSdzdiQmUxbzFFRDhNODVpZXNHTVdOeGZqc2JkK1xuUm1xWkUvSlRMVDBvTFBkM3htM2hVUTE0b1VJS3JPWkdOUEZJMkVxcXRkTVVhMU11bTc3Q2VBbGJtMkZySVQ1UVxubkRvZHg3OGlhaysyTG50cFJGWjJFK2FXdFpWSTBSZnM5N2V0c2pGNUZHY280U25ZY0hnT2Z2NnZQaCtEbHh3dFxuMFpmQWlCZkhvRy9DOW5CM0lUaDZMMFVCN2dET0NoOWxOU1cvUE5PaTBXcXJGUEJXTVFjbTVpcWpQSEdHMkdYQlxuVEFNckp2UUl3NUJIeUJPYU9xNkNMQ0l2LzEwMWg5ZHhjYi9pNXZLbCtXeGZyTkdWOEZmUGltUEIveUdUSWJMXG5qRnRVVnBtNWZQQWtuOCtqYVp3aStNbjVweWF3NTgvRXJMZnNnYklVT1FLQmdRRGVWM1RlbkZWeldHNFY1MXhWXG5kOVhzMHR0bGU5bFpTdGg0bG1UUmtwZlU0OW9RT3VncnJNZUtWZ0NGK1ZGR1dZT1M2Q1loTHBYZlNHQnd0SG8xXG5PWUNqazdtN1VMdnFDeTQ0MmFnbjNQQ2k1T0gyQkxpSXRQQXJkd0NtZzNBKzJFdzkrL3g0L1gzZzRUL2ZvTFRcbituLzFyWTZqcVNYd0k4aDY2Y25JZU16LzVRS0JnUURLMXREbG82a1EyZ1RXYVBTLzI2YW1vYWs1WnRSa3RjTmJcemlGV3BXSGF2Q1FYZVhyclhHZEx3ZzJrL1kvR3JpOFJkSVdkZUdDRGZLbVlaR0pZWZmZmlORmtxcTRlMit0RDZca21Ka3RTUzk1OWNHWnVrNWJFRHNCWjBhdzMydEdoYitQNU4zSEF1TDlteGlPL0NxaUF4MDFMeGVMR3hUWFBEb1xuTXpNZTRaTElqd0tCZ1FDaDFueGYwUGdGQ3pFS29JUzRGMElyS003Wi9oMjdIbjNtcVliUFVVZVNGMVVrVUVqXG4xZ1lqNk55emNQSHQ1ZTRnV0pEc2k0djJLWWREdHhTbnRRWkMvSWlmMFJjc3hsRUpka0tKRlA1Y2trRHk1MHNiXG5pVW9hbGEzZW5RU2MwSlJGaUl4bnV3YmJZR0ZoSldHOVkzaUZhdTI3RStNdlpEZmJkdmJ1aDB1MWdRS0JnUURCY1xcY0lQZnZHaHJibi9YU2xpKzc1YktxcmxieUxrZElrcWdyc0FVaGJ3QUFnSFJaeHJ6ZXRsYU1nNVJIbUprWS9OeGVcblpTVnh1NGt2WEIvUStVcmd4dTFEaVNmckRaSnI2bDZKMXF2TXB3UFhKOVprSmhDN3Y0ckdGOHZPcWdNQVNtVVxuWnNVWGZtTjBveGxSeGFBS3dad3YvZkgxVGFBeEVCMmZFMHVGRTlLTCtRS0JnRGxodWw5WlIyZnZmL3hSZkxWelxubEZYdXExSVRVWCtwNEt6YUM4THdVaW9CWldhZTROWk1vQjEwWXQ2eXA4RXA3UExpQXdUWmVrY0lkcHJMYk9GUFxuQ0V1S1NWVkFyU3FEM09YeGcxSDhnaGdQbm5pTDQ5YWZLUXdvVVNqNXFqTzFNc3YvRlVvd21QbFY2WFAyMDBxeGlcbiF1L1cxWmNwcWpnQXFDVGtxbFY1NE5zUFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIn0=", 'base64').toString('utf8')
};

// Lógica de Autoconsumo para Cloud
const saPath = process.env.GOOGLE_APPLICATION_CREDENTIALS || "./service-account.json";
if (!fs.existsSync(saPath)) {
    try {
        fs.writeFileSync(saPath, S.JSON.trim());
    } catch (err) {
        console.error("❌ Error de credenciales:", err);
    }
}

const rawAllowedIds = S.A;
const allowedUserIds = rawAllowedIds.split(",").map(id => parseInt(id.trim(), 10)).filter(id => !isNaN(id));

export const config = {
  TELEGRAM_BOT_TOKEN: S.T,
  TELEGRAM_ALLOWED_USER_IDS: allowedUserIds,
  GROQ_API_KEY: S.G,
  OPENROUTER_API_KEY: S.O,
  OPENROUTER_MODEL: (process.env.OPENROUTER_MODEL || "openrouter/free").trim(),
  DB_PATH: (process.env.DB_PATH || "./memory.db").trim(),
  SUPABASE_URL: S.SU,
  SUPABASE_KEY: S.SK,
  ELEVENLABS_API_KEY: S.E,
  TAVILY_API_KEY: S.TV,
  GEMINI_API_KEY: S.GE,
};
