name: Keep Hugging Face Space Alive

on:
  schedule:
    # Corre cada 15 minutos
    - cron: '*/15 * * * *'
  # Permite activarlo manualmente
  workflow_dispatch:

jobs:
  ping_huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Mantener el Bot Despierto
        run: |
          curl -I https://safary0328-opengravitybot.hf.space
          echo "Hugging Face Space was pinged to prevent sleeping."
